### ISSUE TITLE
Week 06 - Day 3 - Choose your own API

### ISSUE THREAD

**Issue by gstark** [geekboyisonnow/assignments#20]
In this assignment, you'll build a front end for an API of your choice

![Snowman](./assets/snowman.gif)

## Objectives

- Reinforce component architecture in React
- Reinforce reading of API documentation (some is great, and some is terrible)
- Creating and designing your own features for a web app

## Requirements

We're going to build a front end for an API of your choice. Choose one from [this list](https://github.com/toddmotto/public-apis)

*NOTE* You'll need to choose one with `Auth` being `No` or `apiKey` since we haven't covered `OAuth` authentication yet.

*NOTE* You'll also need to check to see if the API will work from your browser. You can do a quick check by making a small `create-react-app`, doing an `axios.get` or `fetch` of one API URL and see if you get browser errors.

### Explorer Mode

- [ ] Read your API docs
- [ ] Use Postman to make some API requests to be familiar with the API and the data it returns
- [ ] Create a list of the features you are going to create and how they will work
- [ ] Design your User Interface
- [ ] create-react-app
- [ ] Design your HTML statically in `App.js`
- [ ] Make it dynamic
- [ ] Use components when needed
- [ ] Deploy it and share it with friends

**Comment by geekboyisonnow** [comment]
https://github.com/geekboyisonnow/ron-swanson

https://www.beautiful-hour.surge.sh

**Comment by gstark** [comment]
Your homework was marked: **Exceeds Expectations**

![Celebrate ](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ac44f3b65ce52bd3753ea7c498abaacb9cb95e6f/tenor.gif)
> &ldquo;Celebrate &rdquo;
__&mdash; via **[Venel](https://gifs.suncoast.io/venerations/8)**__
